### ISSUE TITLE
Error while verifying the code

### ISSUE THREAD

**Issue by fraserxu** [Seeed-Studio/DataCanvas#1]
Hi @taurindb  I'm running this on Arduino 1.5.6-r2, after following the steps and trying to verify the code, I get this error:

```
Sketch uses 28,732 bytes (100%) of program storage space. Maximum is 28,672 bytes.
Global variables use 987 bytes (38%) of dynamic memory, leaving 1,573 bytes for local variables. Maximum is 2,560 bytes.
processing.app.debug.RunnerException: Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
    at processing.app.Sketch.size(Sketch.java:1676)
    at processing.app.Sketch.build(Sketch.java:1590)
    at processing.app.Sketch.build(Sketch.java:1509)
    at processing.app.Editor$DefaultRunHandler.run(Editor.java:1915)
    at java.lang.Thread.run(Thread.java:695)
```

Anyone has the same issue?

**Comment by fraserxu** [comment]
I fixed it by using Arduino 1.5.8 with Java 7. I guess the core for the newer version for Arduino is smaller than the previous one.

Hope this will help in case someone get the same error.
